root /usr/share/nginx/html/trade-leads/platform-web;
index index.html;

location /api/ {
    proxy_pass http://trade_leads_backend_upstream;
    include /etc/nginx/snippets/proxy-headers.conf;
}

location / {
    try_files $uri $uri/ /index.html;
}
