export type ThemeId = 'paper' | 'figma'

export interface GlobalThemeTokens {
  page: string
  pageAccent: string
  pageDecorPrimary: string
  pageDecorSecondary: string
  surface: string
  surfaceStrong: string
  surfaceSoft: string
  textPrimary: string
  textSecondary: string
  textTertiary: string
  textInverse: string
  borderSoft: string
  borderStrong: string
  accent: string
  accentSoft: string
  accentStrong: string
  success: string
  successSoft: string
  successBorder: string
  danger: string
  dangerSoft: string
  dangerBorder: string
  focusRing: string
  focusOutlineColor: string
  focusOutlineStyle: string
  focusOutlineWidth: string
  focusOutlineOffset: string
  tableHeaderBg: string
  tableHeaderText: string
  inputBackground: string
  inputBackgroundFocus: string
  sidebarStart: string
  sidebarEnd: string
  navItemBackground: string
  navItemActiveBackground: string
  navItemActiveBorder: string
  cardPaperStart: string
  cardPaperEnd: string
  buttonPrimaryBackground: string
  buttonPrimaryText: string
  buttonPrimaryShadow: string
  buttonSoftBackground: string
  tableRowHover: string
  fontBody: string
  fontHeading: string
  fontMono: string
  radiusSm: string
  radiusMd: string
  radiusLg: string
  radiusXl: string
  radiusPill: string
  shadowSoft: string
  shadowCard: string
  motionFast: string
  motionNormal: string
  motionEmphasized: string
  easeStandard: string
}

export const workspaceThemeVarNames = {
  page: '--workspace-page',
  pageAccent: '--workspace-page-accent',
  pageDecorPrimary: '--workspace-page-decor-primary',
  pageDecorSecondary: '--workspace-page-decor-secondary',
  surface: '--workspace-surface',
  surfaceStrong: '--workspace-surface-strong',
  surfaceSoft: '--workspace-surface-soft',
  textPrimary: '--workspace-text-primary',
  textSecondary: '--workspace-text-secondary',
  textTertiary: '--workspace-text-tertiary',
  textInverse: '--workspace-text-inverse',
  borderSoft: '--workspace-border-soft',
  borderStrong: '--workspace-border-strong',
  accent: '--workspace-accent',
  accentSoft: '--workspace-accent-soft',
  accentStrong: '--workspace-accent-strong',
  success: '--workspace-success',
  successSoft: '--workspace-success-soft',
  successBorder: '--workspace-success-border',
  danger: '--workspace-danger',
  dangerSoft: '--workspace-danger-soft',
  dangerBorder: '--workspace-danger-border',
  focusRing: '--workspace-focus-ring',
  focusOutlineColor: '--workspace-focus-outline-color',
  focusOutlineStyle: '--workspace-focus-outline-style',
  focusOutlineWidth: '--workspace-focus-outline-width',
  focusOutlineOffset: '--workspace-focus-outline-offset',
  tableHeaderBg: '--workspace-table-header-bg',
  tableHeaderText: '--workspace-table-header-text',
  inputBackground: '--workspace-input-background',
  inputBackgroundFocus: '--workspace-input-background-focus',
  sidebarStart: '--workspace-sidebar-start',
  sidebarEnd: '--workspace-sidebar-end',
  navItemBackground: '--workspace-nav-item-background',
  navItemActiveBackground: '--workspace-nav-item-active-background',
  navItemActiveBorder: '--workspace-nav-item-active-border',
  cardPaperStart: '--workspace-card-paper-start',
  cardPaperEnd: '--workspace-card-paper-end',
  buttonPrimaryBackground: '--workspace-button-primary-background',
  buttonPrimaryText: '--workspace-button-primary-text',
  buttonPrimaryShadow: '--workspace-button-primary-shadow',
  buttonSoftBackground: '--workspace-button-soft-background',
  tableRowHover: '--workspace-table-row-hover',
  fontBody: '--workspace-font-body',
  fontHeading: '--workspace-font-heading',
  fontMono: '--workspace-font-mono',
  radiusSm: '--workspace-radius-sm',
  radiusMd: '--workspace-radius-md',
  radiusLg: '--workspace-radius-lg',
  radiusXl: '--workspace-radius-xl',
  radiusPill: '--workspace-radius-pill',
  shadowSoft: '--workspace-shadow-soft',
  shadowCard: '--workspace-shadow-card',
  motionFast: '--workspace-motion-fast',
  motionNormal: '--workspace-motion-normal',
  motionEmphasized: '--workspace-motion-emphasized',
  easeStandard: '--workspace-ease-standard'
} satisfies Record<keyof GlobalThemeTokens, string>

export const themeTokenKeys = Object.keys(workspaceThemeVarNames) as Array<keyof GlobalThemeTokens>
